### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by brucou** [pynocchio/pynocchio#100]
Hi,

I am new to Python. I could not build htis from source. How would it work? Many thanks!

**Comment by mstuttgart** [comment]
Hi, you can download `.deb` from here: https://github.com/mstuttgart/pynocchio/releases/tag/3.2.2

To build from source, you need to install de requirements in virtualenv and run the command `python setup.py build_deb` 

To run from source, install requirements in virtualenv and run de script `python pynocchio-client.py`

**Comment by brucou** [comment]
Thanks!!!
