### ISSUE TITLE
Up test coverage to >= 80%

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#68]
Pynocchio install instructions: https://github.com/pynocchio/pynocchio/wiki/Contributing

Any tests is welcome!

**Comment by syre** [comment]
Hey, can i take a look at this?

**Comment by mstuttgart** [comment]
Hi @syre. Yes :+1: 

Any test is welcome!

**Comment by syre** [comment]
@mstuttgart It seems if we want to increase the coverage we also need to test the QtWidget classes, do you have any idea what tools to use for this? I have found this resource so far: https://wiki.python.org/moin/PyQt/GUI_Testing which suggests a lot of options.

**Comment by mstuttgart** [comment]
@syre no idea. I found this tutorial: http://johnnado.com/pyqt-qtest-example/

**Comment by mstuttgart** [comment]
The PyQt is very hard to test. 
I want to rewrite Pynocchio in another framework/language. I think to use [Electron](https://electronjs.org/), [Flask Desktop](https://github.com/smoqadam/PyFladesk) or migrate it to web.

**Comment by syre** [comment]
Ok so this should be abandoned?

**Comment by mstuttgart** [comment]
Hi @syre I want to rewrite Pynocchio from scratch using other framework (migrate to web I guess).
