### ISSUE TITLE
Add log message in Pynocchio core functions

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#70]
Pynocchio install instructions: https://github.com/pynocchio/pynocchio/wiki/Contributing

Add log to follow core functions: 
- [ ] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/bookmark_database_manager.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_factory.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_image.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_rar.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_tar.py
- [x] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_zip.py
- [ ] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/main_window_view.py#L79
- [ ] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/main_window_view.py#L56
- [ ] https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/settings_manager.py

**Comment by sgaist** [comment]
Hi,

Can you give more details about what you would like to log ? And what do you mean by "in system" ?

**Comment by mstuttgart** [comment]
Hi @sgaist 

1. Can you give more details about what you would like to log ?
> I want add logging message on core functions of Pynocchio like file extractor, file loader, add and remove bookmarks actions.
2.  And what do you mean by "in system" ?
> in Pynocchio

**Comment by sgaist** [comment]
Most of them seems already pretty thoroughly doing logging. Are you thinking about adding lines when you raise exceptions ?

**Comment by mstuttgart** [comment]
Yes. You can add logging to describe same work of Pynocchio, for example:

* In [this method](https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_rar.py#L39), you can add a message "Opening rar file",
* In [this line](https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/comic_file_loader_rar.py#L59) add a message "Rar file extract successfully".

**Comment by sgaist** [comment]
Ok, so in fact trace everything that is happening in the application ?

**Comment by mstuttgart** [comment]
Yes. :+1:

**Comment by sgaist** [comment]
Since you re-opened the issue, what parts did I miss ?

**Comment by mstuttgart** [comment]
Add loggin in `main_window_view`, `main_window_model` and `settings_manager`
