### ISSUE TITLE
Add support to CB7

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#73]
Add support to 7zip format

Pynocchio install instructions: https://github.com/pynocchio/pynocchio/wiki/Contributing

**Comment by pandeazucar** [comment]
Hello, I am still reading the documentation for testing but seems to me the best way would be to make an external call to the 7zip program installed on the machine. All the python libraries I could find supporting the archive format are either deprecated or unsupported. I am looking forward to my pull request!

**Comment by mstuttgart** [comment]
Hi @pandeazucar. Thanks for you work.

I see, no problem. You can do call to external 7zip

We can put a verification if the 7zip is installed to. If it is installed, we add the 7zip extension in this list [here](https://github.com/pynocchio/pynocchio/blob/develop/pynocchio/main_window_view.py#L68)
