### ISSUE TITLE
Create RPM package

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#75]
Create package to Fedora OS

Pynocchio install instructions: https://github.com/pynocchio/pynocchio/wiki/Contributing

**Comment by ndcampbell** [comment]
What are you looking for in this issue? Do you want an RPM spec file created and uploaded to the repo or where do you want the RPM uploaded to?

**Comment by mstuttgart** [comment]
Hi @ndcampbell, i want a spec file.

To create `.deb` files, I use [this script](https://github.com/pynocchio/pynocchio/blob/develop/scripts/build_deb.sh) .

This script use PyInstaller to build a binary file and package it in .deb file.

I want a script that make the same thing, but generate a `.rpm` package.
