### ISSUE TITLE
Create Windows executable

### ISSUE THREAD

**Issue by mstuttgart** [pynocchio/pynocchio#76]
Use PyInstaller and the `pynocchio.spec` presente in repository to build a Windows version

**Comment by quatroka** [comment]
I'll start working on it!

**Comment by mstuttgart** [comment]
@quatroka thanks!

**Comment by quatroka** [comment]
I tried to generate the build, it compiled perfectly (after several settings of environment variables), pynocchioe.exe start normally but when I opened an image it broke, I looked for several ways to solve the problems, but I could not, so I gave up While.

My Advances:

To fix warnings on build (set all missing DDLs in environment variables of windows):

- Mysql Connector
- Postgresql
- Microsoft Visual C ++ 2015 Redistributable Update 3 RC
- PyInstaller-Hooks

Good luck for the next one that you try xD.

**Comment by mstuttgart** [comment]
@quatroka ok thanks for advices!
